export const AUTH_SESSION_SET = "AUTH/SESSION_SET" as const
export const AUTH_SESSION_CLEAR = "AUTH/SESSION_CLEAR" as const
export const AUTH_INITIALIZED_SET = "AUTH/INITIALIZED_SET" as const

export const TENANT_PROFILE_SET = "TENANT/PROFILE_SET" as const
export const TENANT_PROFILE_CLEAR = "TENANT/PROFILE_CLEAR" as const
